language: python
python:
- '3.6'
- '3.7'
install:
- pip install tox-travis
script:
- tox
before_deploy:
- pip install poetry
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry config repositories.debonzi https://pypi.debonzi.dev/simple/
deploy:
  - provider: script
    script: poetry publish -n --build -u $PYPI_USER -p $PYPI_PASSWORD
    on:
      branch: master
      python: '3.7'
      tags: true
  - provider: script
    script: poetry publish -n --build -r debonzi -u $PYPI_USER -p $PYPI_PASSWORD
    on:
      branch: development
      python: '3.7'
      tags: true
